"""add updated_at to trees

Revision ID: 0c4c328af214
Revises: c0c7baab5e5f
Create Date: 2026-09-04 17:34:51.598084

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0c4c328af214'
down_revision: Union[str, None] = 'c0c7baab5e5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tree_image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tree_id', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['tree_id'], ['trees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tree_image_id'), 'tree_image', ['id'], unique=False)
    op.create_index(op.f('ix_tree_image_tree_id'), 'tree_image', ['tree_id'], unique=False)
    op.drop_index('ix_tree_images_id', table_name='tree_images')
    op.drop_table('tree_images')
    op.add_column('trees', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('trees', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.create_index(op.f('ix_trees_latitude'), 'trees', ['latitude'], unique=False)
    op.create_index(op.f('ix_trees_longitude'), 'trees', ['longitude'], unique=False)
    op.create_index(op.f('ix_trees_status'), 'trees', ['status'], unique=False)
    op.create_index(op.f('ix_trees_uploader_id'), 'trees', ['uploader_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trees_uploader_id'), table_name='trees')
    op.drop_index(op.f('ix_trees_status'), table_name='trees')
    op.drop_index(op.f('ix_trees_longitude'), table_name='trees')
    op.drop_index(op.f('ix_trees_latitude'), table_name='trees')
    op.alter_column('trees', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.drop_column('trees', 'updated_at')
    op.create_table('tree_images',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('tree_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('image_url', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['tree_id'], ['trees.id'], name='tree_images_tree_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='tree_images_pkey')
    )
    op.create_index('ix_tree_images_id', 'tree_images', ['id'], unique=False)
    op.drop_index(op.f('ix_tree_image_tree_id'), table_name='tree_image')
    op.drop_index(op.f('ix_tree_image_id'), table_name='tree_image')
    op.drop_table('tree_image')
    # ### end Alembic commands ###
