"""add cart expiry and product reservation

Revision ID: 130cf5b99b6e
Revises: 0c4c328af214
Create Date: 2026-09-05 10:05:53.365908

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '130cf5b99b6e'
down_revision: Union[str, None] = '0c4c328af214'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart', sa.Column('expires_at', sa.DateTime(), nullable=True))
    op.add_column('products', sa.Column('reserved_quantity', sa.Integer(), nullable=True))
    op.add_column('products', sa.Column('reservation_expires_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'reservation_expires_at')
    op.drop_column('products', 'reserved_quantity')
    op.drop_column('cart', 'expires_at')
    # ### end Alembic commands ###
