"""add delivery fields to orders

Revision ID: 2f6ccba8ffef
Revises: 177f2a86ae29
Create Date: 2026-08-28 22:24:13.689118

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f6ccba8ffef'
down_revision: Union[str, None] = '177f2a86ae29'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cart', 'quantity',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index('ix_cart_product_id', table_name='cart')
    op.drop_index('ix_cart_user_id', table_name='cart')
    op.drop_constraint('unique_user-product', 'cart', type_='unique')
    op.drop_index('ix_order_items_order_id', table_name='order_items')
    op.drop_index('ix_order_items_product_id', table_name='order_items')
    op.add_column('orders', sa.Column('razorpay_payment_id', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('delivery_address', sa.Text(), nullable=True))
    op.add_column('orders', sa.Column('delivery_phone', sa.String(length=15), nullable=True))
    op.alter_column('orders', 'payment_status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.drop_index('ix_orders_payment_status', table_name='orders')
    op.drop_index('ix_orders_user_id', table_name='orders')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_orders_user_id', 'orders', ['user_id'], unique=False)
    op.create_index('ix_orders_payment_status', 'orders', ['payment_status'], unique=False)
    op.alter_column('orders', 'payment_status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.drop_column('orders', 'delivery_phone')
    op.drop_column('orders', 'delivery_address')
    op.drop_column('orders', 'razorpay_payment_id')
    op.create_index('ix_order_items_product_id', 'order_items', ['product_id'], unique=False)
    op.create_index('ix_order_items_order_id', 'order_items', ['order_id'], unique=False)
    op.create_unique_constraint('unique_user-product', 'cart', ['user_id', 'product_id'])
    op.create_index('ix_cart_user_id', 'cart', ['user_id'], unique=False)
    op.create_index('ix_cart_product_id', 'cart', ['product_id'], unique=False)
    op.alter_column('cart', 'quantity',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
