"""add address fields to users and trees

Revision ID: c0c7baab5e5f
Revises: 9c8f3a2d4b11
Create Date: 2026-09-04 16:40:29.451148

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c0c7baab5e5f'
down_revision: Union[str, None] = '9c8f3a2d4b11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tree_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tree_id', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['tree_id'], ['trees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tree_images_id'), 'tree_images', ['id'], unique=False)
    op.drop_index('ix_tree_image_id', table_name='tree_image')
    op.drop_index('ix_tree_image_tree_id', table_name='tree_image')
    op.drop_table('tree_image')
    op.add_column('trees', sa.Column('village_city', sa.String(length=100), nullable=True))
    op.add_column('trees', sa.Column('district', sa.String(length=100), nullable=True))
    op.add_column('trees', sa.Column('state', sa.String(length=100), nullable=True))
    op.add_column('trees', sa.Column('pincode', sa.String(length=10), nullable=True))
    op.add_column('trees', sa.Column('full_address', sa.String(length=300), nullable=True))
    op.alter_column('trees', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.drop_index('ix_trees_latitude', table_name='trees')
    op.drop_index('ix_trees_longitude', table_name='trees')
    op.drop_index('ix_trees_status', table_name='trees')
    op.drop_index('ix_trees_uploader_id', table_name='trees')
    op.drop_column('trees', 'updated_at')
    op.add_column('users', sa.Column('village_city', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('district', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('state', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('pincode', sa.String(length=10), nullable=True))
    op.add_column('users', sa.Column('full_address', sa.String(length=300), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'full_address')
    op.drop_column('users', 'pincode')
    op.drop_column('users', 'state')
    op.drop_column('users', 'district')
    op.drop_column('users', 'village_city')
    op.add_column('trees', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.create_index('ix_trees_uploader_id', 'trees', ['uploader_id'], unique=False)
    op.create_index('ix_trees_status', 'trees', ['status'], unique=False)
    op.create_index('ix_trees_longitude', 'trees', ['longitude'], unique=False)
    op.create_index('ix_trees_latitude', 'trees', ['latitude'], unique=False)
    op.alter_column('trees', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.drop_column('trees', 'full_address')
    op.drop_column('trees', 'pincode')
    op.drop_column('trees', 'state')
    op.drop_column('trees', 'district')
    op.drop_column('trees', 'village_city')
    op.create_table('tree_image',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('tree_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('image_url', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['tree_id'], ['trees.id'], name='tree_image_tree_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='tree_image_pkey')
    )
    op.create_index('ix_tree_image_tree_id', 'tree_image', ['tree_id'], unique=False)
    op.create_index('ix_tree_image_id', 'tree_image', ['id'], unique=False)
    op.drop_index(op.f('ix_tree_images_id'), table_name='tree_images')
    op.drop_table('tree_images')
    # ### end Alembic commands ###
